# Backend/Automation/content_writer.py
# Jarvis AI — Smart Content Writer
# ─────────────────────────────────────────────────────────────────────────────
# FEATURES:
#   ✅ Generate articles / essays using AI
#   ✅ Create study notes
#   ✅ Generate quiz questions
#   ✅ Summarize topics
#   ✅ Explain concepts in simple language
#   ✅ Auto-open in Notepad
#   ✅ 8GB RAM safe (llama-3.1-8b via Groq API)
#
# VOICE COMMANDS:
#   "content machine learning"
#   "write article on artificial intelligence"
#   "explain quantum computing in simple words"
#   "generate quiz on python"
#   "summarize neural networks"
# ─────────────────────────────────────────────────────────────────────────────

from __future__ import annotations

import datetime
import subprocess
from pathlib import Path

from dotenv import dotenv_values
from .notifier import notify

_env       = dotenv_values(".env")
DATA_DIR   = Path(_env.get("DataDir", "Data"))
GROQ_KEY   = _env.get("GroqAPIKey") or _env.get("GROQ_API_KEY", "")
GROQ_MODEL = _env.get("GroqModel", "llama-3.1-8b-instant")
USERNAME   = _env.get("Username", "User")
DATA_DIR.mkdir(parents=True, exist_ok=True)


def _sanitize(name: str) -> str:
    invalid = '<>:"/\\|?* '
    return "".join(c if c not in invalid else "_" for c in name)[:80]


def _ai_generate(system_prompt: str, user_prompt: str, max_tokens: int = 1000) -> str:
    if not GROQ_KEY:
        return f"[No AI key found]\n\nContent about: {user_prompt}"
    try:
        from groq import Groq  # type: ignore
        client = Groq(api_key=GROQ_KEY)
        resp   = client.chat.completions.create(
            model    = GROQ_MODEL,
            messages = [
                {"role": "system", "content": system_prompt},
                {"role": "user",   "content": user_prompt},
            ],
            max_tokens  = max_tokens,
            temperature = 0.7,
            stream      = False,
        )
        return resp.choices[0].message.content.strip()
    except Exception as e:
        print(f"[red]AI generate failed:[/red] {e}")
        return f"Content about: {user_prompt}"


def _save_and_open(filename: str, content: str) -> Path:
    path = DATA_DIR / filename
    path.write_text(content, encoding="utf-8")
    try:
        subprocess.Popen(["notepad.exe", str(path)])
    except Exception:
        pass
    return path


def Content(topic: str) -> str | None:
    """
    Generate a long-form article on any topic.
    Voice: "content machine learning", "write article on AI"
    """
    print(f"[cyan]Generating content on:[/cyan] {topic}")
    content = _ai_generate(
        system_prompt=(
            "You are an expert content writer. Write well-structured, "
            "informative content with clear headings and examples."
        ),
        user_prompt=(
            f"Write a comprehensive article on: {topic}\n"
            "Include: Introduction, Main Concepts, Examples, Applications, Conclusion.\n"
            "Format with clear headings using ===. Write 500-700 words."
        ),
        max_tokens=1200,
    )
    ts   = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    name = f"Content_{_sanitize(topic)}_{ts}.txt"
    header = (
        f"TOPIC: {topic.upper()}\n"
        f"Generated by Jarvis AI | {datetime.datetime.now().strftime('%d %B %Y %I:%M %p')}\n"
        f"{'='*60}\n\n"
    )
    path = _save_and_open(name, header + content)
    print(f"[bold green]✅ Content saved:[/bold green] {path}")
    notify("Jarvis — Content Created 📄", f"Article on: {topic}")
    return content


def ExplainTopic(topic: str) -> str | None:
    """
    Explain a topic in simple, easy language.
    Voice: "explain machine learning in simple words"
            "explain recursion like I'm a beginner"
    """
    print(f"[cyan]Explaining:[/cyan] {topic}")
    content = _ai_generate(
        system_prompt=(
            "You are a teacher explaining topics to a student. "
            "Use simple language, real-world analogies, and short examples."
        ),
        user_prompt=(
            f"Explain '{topic}' in very simple terms.\n"
            "Use an analogy, a real example, and keep it under 300 words."
        ),
        max_tokens=500,
    )
    print(f"\n[bold cyan]💡 Explanation:[/bold cyan]\n{content}\n")
    notify("Jarvis — Explanation", f"Explained: {topic}")
    return content


def GenerateQuiz(topic: str) -> str | None:
    """
    Generate quiz questions on any topic.
    Voice: "generate quiz on python", "quiz me on machine learning"
    """
    print(f"[cyan]Generating quiz on:[/cyan] {topic}")
    content = _ai_generate(
        system_prompt=(
            "You are a quiz generator. Create clear, educational MCQ questions."
        ),
        user_prompt=(
            f"Generate 5 multiple choice questions on: {topic}\n"
            "Format each as:\nQ1. [Question]\na) [Option]\nb) [Option]\n"
            "c) [Option]\nd) [Option]\nAnswer: [correct letter]"
        ),
        max_tokens=700,
    )
    ts   = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
    name = f"Quiz_{_sanitize(topic)}_{ts}.txt"
    header = (
        f"QUIZ: {topic.upper()}\n"
        f"Generated by Jarvis AI | {datetime.datetime.now().strftime('%d %B %Y')}\n"
        f"{'='*60}\n\n"
    )
    path = _save_and_open(name, header + content)
    print(f"[bold green]✅ Quiz saved:[/bold green] {path}")
    notify("Jarvis — Quiz Ready 🧪", f"Quiz on: {topic}")
    return content


def SummarizeTopic(topic: str) -> str | None:
    """
    Give a quick summary of any topic.
    Voice: "summarize neural networks", "briefly explain blockchain"
    """
    print(f"[cyan]Summarizing:[/cyan] {topic}")
    content = _ai_generate(
        system_prompt="You are an expert at creating concise, accurate summaries.",
        user_prompt=(
            f"Give a concise summary of: {topic}\n"
            "Max 5 bullet points. Each point max 2 sentences."
        ),
        max_tokens=300,
    )
    print(f"\n[bold cyan]📋 Summary of {topic}:[/bold cyan]\n{content}\n")
    notify("Jarvis — Summary", f"Summarized: {topic}")
    return content